services:
  servermanagerbot:
    image: ghcr.io/erfjab/servermanagerbot:latest
    restart: always
    env_file:
      - .env
    network_mode: "host"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      # Direct reference to variables in .env
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"

volumes:
  postgres_data:
